blog/config/routes.rb
Blog::Application.routes.draw do

  resources :users

  resources :people

      root :to => "welcome#index"
      get "welcome" => "welcome#index"
      get "welcome/say_hello" => "welcome#say"
      get "service" => "welcome#service"

      get 'index' => "welcome#index"
    
      get 'team' => 'welcome#team'

      get 'user'=>'welcome#user'

end

blog/app/models/person.rb
class Person < ActiveRecord::Base
end

blog/app/models/user.rb
class User < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



	def index

		puts 1 + 2
		
	end


	def say
		
	end

	def service
		
	end


	def team

	end


	def user

	end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/people_helper.rb
module PeopleHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R&M</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

blog/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

blog/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

blog/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

blog/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

blog/app/views/welcome/index.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
       
       
        <%= stylesheet_link_tag    "css" %><%= stylesheet_link_tag    "lanrenzhijia" %><%= stylesheet_link_tag    "txcssx" %>
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
        <script type="text/javascript" src="/assets/jquery-1.8.0.min.js">
</script>
        <script type="text/javascript" src="/assets/lanrenzhijia.js">
</script>
        <title>ddddd</title>
    </head>
    <body>
        <!--qq代码结束-->
        <div class="head">
            <div class=" headk">
                <div id="logo">
                    <img src="/assets/icon4(ms).png" width="50" height="50" alt="logo">
                </div>
                <div id="menu">
                    <ul>
                        <li>
                            <a href="welcome" style="border-bottom:2px #2dc1f8 solid; color:#2dc1f8;">首页</a>
                        </li>
                        <li>
                            <a href="service">案例</a>
                        </li>
                       <!--  <li>
                            <a href="#">团队</a>
                        </li>
                        <li>
                            <a href="＃">关于</a>
                        </li>
                        <li>
                            <a href="#">登录</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </div>
        <div id="tou"></div>
        <div id="full-screen-slider">
            <div class="syfdan">
                <div class="syfdany">
                    <div class="syfdanylf"></div><!--<div class="anxwz">(注册即获赠免费体验)</div>-->
                </div>
            </div>
            <ul id="slides" style="z-index: 99;">

               <li style="background-image: url(http://localhost:3000/assets/01.jpg); z-index: 900; display: block; background-position: 50% 0%; background-repeat: no-repeat no-repeat;"> </li>
    <li style="background-image: url(http://localhost:3000/assets/02.jpg); z-index: 800;display: none; background-position: 50% 0%; background-repeat: no-repeat no-repeat;"> </li>
      <li style="background-image: url(http://localhost:3000/assets/03.jpg); display: none; background-position: 50% 0%; background-repeat: no-repeat no-repeat;"> </li>
      <li style="background-image: url(http://localhost:3000/assets/04.jpg); display: none; background-position: 50% 0%; background-repeat: no-repeat no-repeat;"> </li>
            </ul>
        </div>
        <div class="dkk">
            <div class="dkklm" style="height:440px;">
                <div class="ye" style="padding-top:30px;">
                    <div class="yskk">
                        <div class="yskks" onclick="location.href='service.html#oa'" style="cursor:pointer;">
                            <div class="yskks_img">
                                <img src="/assets/ys01.png" width="60" height="60" alt="移动OA">
                            </div>
                            <div class="yskks_wz">
                                微信OA
                            </div>
                        </div>
                        <div class="yskkx">
                            <strong>R&M，为企业量身定做的移动办公、团队协同、微信公众平台。</strong>
                        </div>
                        <div class="yskkxb">
                           随时随地在线发布通知公告、会议管理，团队信息流通畅；快速实现流程审批、出差申请、费用申请，团队工作流通畅；管理员汇总考勤记录、出差记录，了解团队出勤状况。 R&M，简化办公流程，提高办公效率！
                        </div>
                    </div>
                    <div class="yskk" style="padding-left:47px;">
                        <div class="yskksa" onclick="location.href='service.html#wq'">
                            <div class="yskks_img">
                                <img src="/assets/ys02.png" width="60" height="60" alt="移动外勤">
                            </div>
                            <div class="yskks_wz">
                                微信外勤
                            </div>
                        </div>
                        <div class="yskkxa">
                            <strong>R&M，外勤人员的便捷工作平台，外勤团队的高效管理工具。</strong>
                        </div>
                        <div class="yskkxb">
                          外勤人员便捷记录外勤过程，及时汇报外勤工作状况；管理者灵活查阅外勤汇总路线，了解外勤人员工作实况，合理分配外勤任务。 R&M，简化外勤团队管理，提高外勤人员的办公效率，外勤团队尽在“掌”控。
                        </div>
                    </div>
                    <div class="yskk" style="padding-left:47px;">
                        <div class="yskksg" onclick="location.href='service.html#cr'">
                            <div class="yskks_img">
                                <img src="/assets/ys03.png" width="60" height="60" alt="移动CRM">
                            </div>
                            <div class="yskks_wz">
                                微信CRM 
                            </div>
                        </div>
                        <div class="yskkxg">
                            <strong>R&M，全景式客户信息采集，全程化销售过程管理。</strong>
                        </div>
                        <div class="yskkxb">
                            拓展人员随时随地建立、维护客户信息，管理者随时随地管理、使用客户信息，客户资源分权使用；管理者为拓展人员提供一对一的指点。团队分工合作，形成良性客户拓展模式。R&M，提高客户资源价值转化率！
                        </div>
                    </div>
                    <div class="yskk" style="padding-left:47px;">
                        <div class="yskksc" onclick="location.href='service.html#xs'">
                            <div class="yskks_img">
                                <img src="/assets/ys04.png" width="60" height="60" alt="移动营销">
                            </div>
                            <div class="yskks_wz">
                                微信营销
                            </div>
                        </div>
                        <div class="yskkxc">
                            <strong>R&M，实时采集销售数据，及时生成智能报表分析。</strong>
                        </div>
                        <div class="yskkxb">
                            营销人员在手机上实时操作销售上报、入库盘点、库存管理、订单管理，管理人员实时查看销售报表、趋势分析、竞争分析，并制定销售计划。用数据支持决策，让销售决策更科学。 R&M，让营销团队更智能！
                        </div>
                    </div>
                </div>
        </div>
        <div class="main_foot">
            <div class="foot">
               
                <ul class="list3">
                    <li>
                        <!-- 网站h1修改-->
                        <span>关于</span>
                    </li>
                    
                    <li>
                        <a href="team">R&M信息安全</a>
                    </li>
                    <li>
                        <a href="user">R&M用户协议</a>
                    </li>
                </ul>
                <ul class="list3">
                    <li>
                        <!-- 网站h1修改-->
                        <span>合作</span>
                    </li>
                   
                    <li>
                        <a href="%EF%BC%83">商务合作：zzlmilk@icloud.com</a>
                    </li>
                    <li>电话：15901794453
                    </li>
                   
                </ul>
                <ul class="list4">
                    <li>
                        <span>联系我们</span>
                    </li>
                    <li>
电话：15901794453
                    </li>
                    <li>QQ：413124766
                    </li>
                  
                </ul>
            </div>
        </div>
        <div class="zuidibu">
            <div class="zuidibuzj">
                Copyright © 2012 - 2014 上海R&M有限公司。
            </div>
        </div><script type="text/javascript">
var default_view = 1; <!--1是默认展开，0是默认关闭，新开窗口看效果，别在原页面刷新-->
        </script><script type="text/javascript" src="/assets/txqqx.js">
</script>
    </body>
</html>

blog/app/views/welcome/say.html.erb
<h1>Hello, World!</h1>

<p><%= link_to "Home", root_path %></p>

blog/app/views/welcome/service.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>
            R&M,一站式移动信息化服务平台，广东马上信息科技有限公司
        </title>
        <meta content="移动协同，移动OA，移动办公，移动外勤，移动营销，移动CRM，手机OA,马上信息" name="keywords">
        <meta content="R&M，一站式移动信息化服务平台，是企业移动协同系统领导品牌，专业提供移动办公，移动OA，移动外勤，移动营销，移动CRM，手机OA，按需定制软件等信息化整体解决方案，提供免费下载试用，咨询热线：4000224009" name="description"><%= stylesheet_link_tag    "css" %><%= stylesheet_link_tag    "lanrenzhijia" %><%= stylesheet_link_tag    "txcssx" %><%= stylesheet_link_tag    "homef" %>
        <script type="text/javascript" src="/assets/jquery-1.8.0.min.js">
</script>
        <script type="text/javascript" src="/assets/lanrenzhijia.js">
</script>
        <script src="/assets/jquery.flow.1.2.js" type="text/javascript">
</script>
        <script language="javascript" type="text/javascript">
var Then = new Date(); 
        Then.setTime(Then.getTime() + 12*60*60*1000 ); //秒分 
        var cookieString = new String(document.cookie); 
        var cookieHeader = "POPWIN" ; 
        var beginPosition = cookieString.indexOf(cookieHeader); 
        if (beginPosition == -1) 
        { 
        var newtop=0 
        var newleft=0 
        if (navigator.appName == "Netscape") { 
        layerStyleRef="layer."; 
        layerRef="document.layers"; 
        styleSwitch=""; 
        } 
        else 
        { 
        layerStyleRef="layer.style."; 
        layerRef="document.all"; 
        styleSwitch=".style"; 

        } 
        var autoclick_ok=false; 
        function toExit(){ 
        autoclick_ok=true; 
        document.cookie = "Cookie9=POPWIN;expires="+ Then.toGMTString() +";path=/"; 
        } 

        function doMouseMove() { 

        layerName = 'iit' 
        eval('var curElement='+layerRef+'["'+layerName+'"]') 
        eval(layerRef+'["'+layerName+'"]'+styleSwitch+'.visibility="hidden"') 
         
        if(!autoclick_ok) 
        { 
            eval('curElement'+styleSwitch+'.visibility="visible"') 
        }else{ 
            eval('curElement'+styleSwitch+'.visibility="hidden"') 
        } 
         
        eval('newleft=document.body.clientWidth-curElement'+styleSwitch+'.pixelWidth') 
        eval('newtop=document.body.clientHeight-curElement'+styleSwitch+'.pixelHeight') 
        eval('height=curElement'+styleSwitch+'.height') 
        eval('width=curElement'+styleSwitch+'.width') 
        width=parseInt(width) 
        height=parseInt(height) 
        if (event.clientX > (document.body.clientWidth - 10 - width)) 
        { 
        newleft=document.body.clientWidth + document.body.scrollLeft - 10 - width 
        } 
        else 
        { 
        newleft=document.body.scrollLeft + event.clientX-10 
        } 
        eval('curElement'+styleSwitch+'.pixelLeft=newleft') 

        if (event.clientY > (document.body.clientHeight - 5 - height)) 
        { 
        newtop=document.body.clientHeight + document.body.scrollTop - 5 - height 
        } 
        else 
        { 
        newtop=document.body.scrollTop + event.clientY-10 
        } 
        eval('curElement'+styleSwitch+'.pixelTop=newtop') 
        } 

        document.onmousemove = doMouseMove; 

        if (navigator.appName == "Netscape") { 

        } 
        else 
        { 

        } 
        }
        </script>
        <script type="text/javascript">
$(document).ready(function() {  

        $(function() {
        $("div#controller").jFlow({     
        slides: "#slides",
        controller: ".flowctrl", 
        slideWrapper : "#jFlowSlide", 
        selectedWrapper: "jFlowSelected", 
        width: "960px",
        height: "500px",
        duration: 400,
        prev: ".flowprev", 
        next: ".flownext" 
        });
        });
        $(".overlay h1").click(function(){ 
        window.location=$(this).find("a").attr("href");return false;
        });
        $(".bottom-block").hover(function() { 
        $(this).addClass("bottom-block-over");    
        }, function() {
        $(this).removeClass("bottom-block-over"); 
        }); 
        $(".bottom-block").click(function(){ 
        window.location=$(this).find("a").attr("href");return false;
        });
        }); 
        </script>
        <script type="text/javascript">
window.onload=function clear_a(){
        var a;
        for(var i=0;(a=document.getElementsByTagName("a")[i]);i++){
        if(a.getAttribute("onfocus")==null){
        a.setAttribute("onfocus","this.blur();");
        }else{
        a.setAttribute("onfoucs",a.getAttribute("onfocus")+";this.blur();");}
        a.setAttribute("hideFocus","hidefocus");
        }
        }
        </script>
    </head>
    <body>
        <div class="head">
            <div class=" headk">
                <div id="logo">
                    <img src="/assets/icon4(ms).png" width="50" height="50" alt="logo">
                </div>
                <div id="menu">
                    <ul>
                        <li>
                            <a href="welcome" >首页</a>
                        </li>
                        <li>
                            <a href="service" >案例</a>
                        </li>
                       <!--  <li>
                            <a href="#">团队</a>
                        </li>
                        <li>
                            <a href="＃">关于</a>
                        </li>
                        <li>
                            <a href="#">登录</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </div>
        <div id="tou"></div>
        <div class="dkk">
            <div class="dkklm" style=" padding-bottom:30px;">
                <div id="container">
                    <div id="content">
                        <div id="jFlowSlide" style="position: relative; width: 960px; height: 500px; overflow: hidden;">
                            <div id="slides" style="position: relative; width: 4800px; height: 500px; overflow: hidden; margin-left: 0px;">
                                <div class="jFlowSlideContainer" style="position: relative; width: 960px; height: 500px; float: left; overflow: auto;">
                                    <div class="slide sl-home">
                                        <p class="more"></p>
                                    </div>
                                </div>
                                <div class="jFlowSlideContainer" style="position: relative; width: 960px; height: 500px; float: left; overflow: auto;">
                                    <div class="slide sl-featured"></div>
                                </div>
                                <div class="jFlowSlideContainer" style="position: relative; width: 960px; height: 500px; float: left; overflow: auto;">
                                    <div class="slide sl-portfolio"></div>
                                </div>
                                <div class="jFlowSlideContainer" style="position: relative; width: 960px; height: 500px; float: left; overflow: auto;">
                                    <div class="slide sl-about"></div>
                                </div>
                                <div class="jFlowSlideContainer" style="position: relative; width: 960px; height: 500px; float: left; overflow: auto;">
                                    <div class="slide sl-portfoliof"></div>
                                </div><!--<DIV class="slide sl-portfoliof"></DIV>-->
                            </div>
                        </div>
                        <ul id="pagination" style="z-index:100"></ul>
                        <div id="controller">
                            <span class="flowprev"><a href="#" onfocus="this.blur();" hidefocus="hidefocus">&lt;</a></span> <span class="flowctrl jFlowSelected" style="width:165px;"><a href="#" onfocus="this.blur();" hidefocus="hidefocus"><span style="line-height:50PX; width:100px;">上午 休息室&nbsp;PC</span></a></span> <span class="flowctrl" style="width:165px;"><a href="#" onfocus="this.blur();" hidefocus="hidefocus"><span style="line-height:50PX; width:100px;">上午 酒店&nbsp;手机</span></a></span> <span class="flowctrl" style="width:165px;"><a href="#" onfocus="this.blur();" hidefocus="hidefocus"><span style="line-height:50PX; width:100px;">中午 机场&nbsp;Pad</span></a></span> <span class="flowctrl" style="width:165px;"><a href="#" onfocus="this.blur();" hidefocus="hidefocus"><span style="line-height:50PX; width:100px;">下午 咖啡厅&nbsp;手机</span></a></span> <span class="flowctrl" style="width:165px;"><a href="#" onfocus="this.blur();" hidefocus="hidefocus"><span style="line-height:50PX; width:100px;">傍晚 办公室&nbsp;PC</span></a></span> <span class="flownext"><a href="#" onfocus="this.blur();" hidefocus="hidefocus">&gt;</a></span>
                        </div>
                    </div>
                </div><!--<div class="sytp" ><img src="images/gg.jpg" width="960" height="228" /></div>-->
                <!--一大列开始-->
                <div class="fud">
                    <!--第一列-->
                    <!--真正开始-->
                    <a name="oa" onfocus="this.blur();" hidefocus="hidefocus"></a>
                    <div class="fuwu" style="padding-top:70px;">
                       
                    </div>
                </div>
            </div>
            <div class="main_foot">
            <div class="foot">
               
                <ul class="list3">
                    <li>
                        <!-- 网站h1修改-->
                        <span>关于</span>
                    </li>
                   
                    <li>
                        <a href="team">R&M信息安全</a>
                    </li>
                    <li>
                        <a href="user">R&M用户协议</a>
                    </li>
                </ul>
                <ul class="list3">
                    <li>
                        <!-- 网站h1修改-->
                        <span>合作</span>
                    </li>
                  
                    <li>
                        <a href="javascript:void(0)">商务合作：zzlmilk@icloud.com</a>
                    </li>
                    <li>电话：15901794453
                    </li>
                   
                </ul>
                <ul class="list4">
                    <li>
                        <span>联系我们</span>
                    </li>
                    <li>
电话：15901794453
                    </li>
                    <li>QQ：413124766
                    </li>
                  
                </ul>
            </div>
        </div>
        <div class="zuidibu">
            <div class="zuidibuzj">
                Copyright © 2012 - 2014 上海R&M有限公司。
            </div>
        </div>
        </div>
    </body>
</html>